### ISSUE TITLE
Падение при синхронизации

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#60]
Приложение из testfairy (https://tsfr.io/qnu8q5). При синхронизации все время происходит падение.
Пользователь неавторизованный. Создано одно сообщение.

вот детали прилетели
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.nextgis.maplib.notify_update flg=0x10 (has extras) } in com.nextgis.maplib.map.MapContentProviderHelper$VectorLayerNotifyReceiver@21af9450
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5234)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.nextgis.maplib.datasource.GeometryRTree.chooseLeaf(GeometryRTree.java:684)
	at com.nextgis.maplib.datasource.GeometryRTree.chooseLeaf(GeometryRTree.java:706)
	at com.nextgis.maplib.datasource.GeometryRTree.insert(GeometryRTree.java:403)
	at com.nextgis.maplib.datasource.GeometryRTree.addItem(GeometryRTree.java:139)
	at com.nextgis.maplib.map.VectorLayer.cacheGeometryEnvelope(VectorLayer.java:636)
	at com.nextgis.maplib.map.VectorLayer.notifyUpdate(VectorLayer.java:1894)
	at com.nextgis.maplib.map.MapContentProviderHelper$VectorLayerNotifyReceiver.onReceive(MapContentProviderHelper.java:189)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
	... 9 more
```

**Comment by 4eRTuk** [comment]
Это из-за RTree опять.

**Comment by BishopGIS** [comment]
```
java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.Long
	at com.nextgis.safeforest.util.MapUtil.removeOutdatedChanges(MapUtil.java:129)
	at com.nextgis.safeforest.datasource.FVSyncAdapter.sync(FVSyncAdapter.java:44)
	at com.nextgis.maplib.datasource.ngw.SyncAdapter.onPerformSync(SyncAdapter.java:118)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```
