### ISSUE TITLE
Падение при регистрации пользователя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#71]
```
java.lang.NullPointerException
	at com.nextgis.maplibui.fragment.NGWLoginFragment$LocalTextWatcher.afterTextChanged(NGWLoginFragment.java:354)
	at com.nextgis.safeforest.fragment.LoginFragment$EmailWatcher.afterTextChanged(LoginFragment.java:345)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:7455)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9315)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:970)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:497)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:678)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:196)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:318)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:87)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5520)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
	at dalvik.system.NativeStart.main(Native Method)
```

```
java.lang.NullPointerException
	at com.nextgis.maplibui.fragment.NGWLoginFragment$LocalTextWatcher.afterTextChanged(NGWLoginFragment.java:354)
	at com.nextgis.safeforest.fragment.LoginFragment$PasswordWatcher.afterTextChanged(LoginFragment.java:337)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:7455)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9315)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:970)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:497)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:678)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:196)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:318)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:87)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5520)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
	at dalvik.system.NativeStart.main(Native Method)
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextgis.safeforest/com.nextgis.safeforest.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.SwitchCompat.isChecked()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
	at android.app.ActivityThread.access$900(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5258)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.SwitchCompat.isChecked()' on a null object reference
	at com.nextgis.maplibui.fragment.NGWLoginFragment$LocalTextWatcher.afterTextChanged(NGWLoginFragment.java:354)
	at com.nextgis.safeforest.fragment.LoginFragment$URLWatcher.afterTextChanged(LoginFragment.java:353)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:7695)
	at android.widget.TextView.setText(TextView.java:4066)
	at android.widget.TextView.setText(TextView.java:3915)
	at android.widget.EditText.setText(EditText.java:85)
	at android.widget.TextView.setText(TextView.java:3890)
	at android.widget.TextView.onRestoreInstanceState(TextView.java:3790)
	at android.view.View.dispatchRestoreInstanceState(View.java:13740)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
	at android.view.View.restoreHierarchyState(View.java:13718)
	at android.support.v4.app.Fragment.restoreViewState(Fragment.java:471)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1105)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2053)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:543)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
	at android.app.Activity.performStart(Activity.java:6006)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
	... 11 more
```

**Comment by 4eRTuk** [comment]
А это с последним maplib/maplibui собиралось?

**Comment by BishopGIS** [comment]
Да. Но это не нормально вносить в базовую библиотеку такие правки, что все
ломают. К сожалению юнит тестов нет, что бы отловить до коммита.
